class Constants:
    TILE_SIZE = 20  # The size of the square.

    SCREEN_WIDTH = 50 * TILE_SIZE
    SCREEN_HEIGHT = 30 * TILE_SIZE

    LEVEL_CHOICE_X = SCREEN_WIDTH // 2
    LEVEL_CHOICE_Y_BEGIN = 50
    LEVEL_CHOICE_Y_INTERVAL = 120

    FIRST_SQUARE_START_X = 30
    FIRST_SQUARE_START_Y = 40
